name: StatCraft
main: wav.demon.StatCraft
version: 1.0
commands:
  list:
    description: Lists all online players.
    usage: /<command>
  deaths:
    description: Lists total deaths logged of a player
    usage: /<command> [player] or just /<command> to list deaths of yourself
  blocks:
    description: Lists total blocks broken and placed by a player
    usage: /<command> [player] or just /<command> to list blocks of yourself
  resetstats:
    description: Resets the server stats
    usage: /<command> force-all [type] or /<command> force [player] [type]
  printdata:
    description: Prints the data held in statsForPlayers
    usage: /<command>
    permission: StatCraft.killer.*
    permission-message: You don't have <permission>
  updateTotals:
    description: Updates the totals
    usage: /<command>
    permission: StatCraft.killer.*
    permission-message: You don't have <permission>
  playtime:
    description: Lists a player's playtime
    usage: /<command> [player] or just /<command> to list playtime for yourself
  lastseen:
    description: Lists the time a date a player was last seen on the server
    usage: /<command> [player]
  itempickups:
    description: Lists the number of items a player has picked up
    usage: /<command> [player] or just /<command> to list item pickups for yourself
  itemdrops:
    description: Lists the number of items a player has dropped
    usage: /<command> [player] or just /<command> to list item drops for yourself
  itemscrafted:
    description: Lists  the number of items a player has crafted
    usage: /<command> [player] or just /<command> to list items crafted for yourself
  onfire:
    description: Lists how long a player has been on fire
    usage: /<command> [player] or just /<command> to list time on fire for yourself
  toolsbroken:
    description: Lists how many tools a player has broken
    usage: /<command> [player] or just /<command> to list tools broken for yourself
  arrowsshot:
    description: Lists how many arrows a player has shot
    usage: /<command> [player] or just /<command> to list the arrows shot for yourself
  bucketsfilled:
    description: Lists how many buckets a player has filled
    usage: /<command> [player] or just /<command> to list buckets filled for yourself
  bucketsemptied:
    description: Lists how many buckets a player has emptied
    usage: /<command> [player] or just /<command> to list buckets emptied for yourself
permissions:
  killer.kill:
    description: Basically OP
    default: op