name: IRCBot
main: wav.demon.IRCBot
version: 1.0
commands:
  list:
    description: Lists all online players.
    usage: /<command>
  deaths:
    description: Lists total deaths logged of a player
    usage: /<command> [player] or just /<command> to list deaths of yourself
  kill:
    description: Kills a player
    useage: /<command> [player] [arg], [arg] is optional, can be explode or slap
    permission: IRCBot.killer.*
    permission-message: You don't have <permission>
permissions:
  killer.*:
    description: Gives access to OP commands
    children:
      killer.kill: op
      killer.explode: op
      killer.slap: op
  killer.kill:
    description: Allows you to kill a player
    default: op
  killer.explode:
    description: Allows you to kill a player cooler
    default: op
  killer.slap:
    description: Allows you to slap a player
    default: op